apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - image: mysql
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: yunus
      - name: MYSQL_USER
        value: yunus
      - name: MYSQL_PASSWORD
        value: yunus
  volumes:
  - name: mysql-data
    hostPath:
      # chemin du dossier sur l’hôte
      path: /data-volume
      # champ optionnel
      type: Directory
